"""initial schema

Revision ID: 72dc738e6a61
Revises: 
Create Date: 2026-05-02 16:02:35.271837

"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '72dc738e6a61'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('bbox_min_lat', sa.Float(), nullable=False),
    sa.Column('bbox_max_lat', sa.Float(), nullable=False),
    sa.Column('bbox_min_lng', sa.Float(), nullable=False),
    sa.Column('bbox_max_lng', sa.Float(), nullable=False),
    sa.Column('preco_validade_horas_soft', sa.Integer(), nullable=False),
    sa.Column('preco_validade_horas_hard', sa.Integer(), nullable=False),
    sa.Column('stale_coverage_alert_pct', sa.Integer(), nullable=False),
    sa.Column('horizonte_default_km', sa.Float(), nullable=False),
    sa.Column('fator_road_default', sa.Float(), nullable=False),
    sa.Column('is_demo', sa.Integer(), nullable=False),
    sa.CheckConstraint("uf GLOB '[A-Z][A-Z]'", name='ck_cidade_uf_format'),
    sa.CheckConstraint('bbox_min_lat BETWEEN -90 AND 90 AND bbox_max_lat BETWEEN -90 AND 90', name='ck_cidade_bbox_lat'),
    sa.CheckConstraint('bbox_min_lng BETWEEN -180 AND 180 AND bbox_max_lng BETWEEN -180 AND 180', name='ck_cidade_bbox_lng'),
    sa.CheckConstraint('preco_validade_horas_soft <= preco_validade_horas_hard', name='ck_cidade_validade_ordem'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combustivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.CheckConstraint("codigo IN ('gasolina_comum','gasolina_aditivada','etanol','diesel_s10','diesel_s500','gnv')", name='ck_combustivel_codigo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('feature_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('escopo', sa.String(length=10), nullable=False),
    sa.Column('alvo', sa.String(length=60), nullable=False),
    sa.Column('valor_json', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.String(length=40), nullable=False),
    sa.Column('atualizado_por', sa.String(length=80), nullable=False),
    sa.CheckConstraint("escopo IN ('global','cidade','usuario')", name='ck_flag_escopo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave', 'escopo', 'alvo', name='uq_feature_flag_target')
    )
    op.create_table('idempotency_key',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('owner_lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uuid', sa.String(length=40), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('heartbeat_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('perfil', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('opt_in_lgpd', sa.Integer(), nullable=False),
    sa.Column('opt_in_at', sa.String(length=40), nullable=True),
    sa.Column('tombstoned', sa.Integer(), nullable=False),
    sa.Column('tombstoned_at', sa.String(length=40), nullable=True),
    sa.Column('bloqueado_ate', sa.String(length=40), nullable=True),
    sa.Column('export_ultimo_em', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint("perfil IN ('motorista','operador','admin')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('veiculo_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('kml_default_p10', sa.Float(), nullable=False),
    sa.Column('kml_default_p50', sa.Float(), nullable=False),
    sa.Column('kml_default_p90', sa.Float(), nullable=False),
    sa.Column('raio_maximo_km', sa.Float(), nullable=False),
    sa.CheckConstraint('kml_default_p10 <= kml_default_p50 AND kml_default_p50 <= kml_default_p90', name='ck_kml_ordem'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('bot_estado',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=40), nullable=False),
    sa.Column('valor_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('expira_em', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'chave')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('combustivel_id', sa.Integer(), nullable=False),
    sa.Column('autonomia_km', sa.Float(), nullable=False),
    sa.Column('modo', sa.String(length=10), nullable=False),
    sa.Column('volume_alvo_l', sa.Float(), nullable=True),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('feita_em', sa.String(length=40), nullable=False),
    sa.Column('top_n_resultado_json', sa.Text(), nullable=False),
    sa.Column('assumptions_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('anonimizada', sa.Integer(), nullable=False),
    sa.Column('lat_anon', sa.Float(), nullable=True),
    sa.Column('lng_anon', sa.Float(), nullable=True),
    sa.CheckConstraint("modo IN ('parcial','completo')", name='ck_consulta_modo'),
    sa.CheckConstraint('length(assumptions_json) < 4096', name='ck_consulta_assumptions_size'),
    sa.CheckConstraint('length(top_n_resultado_json) < 16384', name='ck_consulta_topn_size'),
    sa.ForeignKeyConstraint(['combustivel_id'], ['combustivel.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.create_index('ix_consulta_feita_em', ['feita_em'], unique=False)
        batch_op.create_index('ix_consulta_usuario', ['usuario_id'], unique=False)

    op.create_table('evento_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=40), nullable=False),
    sa.Column('recurso', sa.String(length=40), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('hash_prev', sa.String(length=64), nullable=False),
    sa.Column('hash_self', sa.String(length=64), nullable=False),
    sa.CheckConstraint('length(payload_json) < 8192', name='ck_audit_payload_size'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_audit', schema=None) as batch_op:
        batch_op.create_index('ix_audit_criado', ['criado_em'], unique=False)

    op.create_table('faixa_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('combustivel_id', sa.Integer(), nullable=False),
    sa.Column('min_centavos', sa.Integer(), nullable=False),
    sa.Column('max_centavos', sa.Integer(), nullable=False),
    sa.Column('max_variacao_pct_24h', sa.Integer(), nullable=False),
    sa.CheckConstraint('min_centavos > 0 AND max_centavos > min_centavos', name='ck_faixa_range'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidade.id'], ),
    sa.ForeignKeyConstraint(['combustivel_id'], ['combustivel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidade_id', 'combustivel_id', name='uq_faixa_preco')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_linhas', sa.Integer(), nullable=False),
    sa.Column('linhas_ok', sa.Integer(), nullable=False),
    sa.Column('linhas_erro', sa.Integer(), nullable=False),
    sa.Column('erros_json', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('staging','commit','rollback','erro')", name='ck_import_status'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidade.id'], ),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('posto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('bandeira', sa.String(length=60), nullable=False),
    sa.Column('endereco', sa.String(length=240), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('lat BETWEEN -90 AND 90 AND lng BETWEEN -180 AND 180', name='ck_posto_latlng_range'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posto', schema=None) as batch_op:
        batch_op.create_index('ix_posto_cidade_ativo', ['cidade_id', 'ativo'], unique=False)

    op.create_table('tombstone_usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.Column('motivo', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('usuario_cidade',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=16), nullable=False),
    sa.CheckConstraint("papel IN ('motorista','operador','admin')", name='ck_usuario_cidade_papel'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'cidade_id')
    )
    op.create_table('veiculo_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('combustivel_id', sa.Integer(), nullable=False),
    sa.Column('km_por_litro', sa.Float(), nullable=False),
    sa.Column('km_por_litro_p10', sa.Float(), nullable=True),
    sa.Column('km_por_litro_p90', sa.Float(), nullable=True),
    sa.CheckConstraint('km_por_litro BETWEEN 0.5 AND 50', name='ck_perfil_kml_range'),
    sa.ForeignKeyConstraint(['combustivel_id'], ['combustivel.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['veiculo_tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abastecimento_relatado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('posto_id', sa.Integer(), nullable=False),
    sa.Column('combustivel_id', sa.Integer(), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('volume_l', sa.Float(), nullable=False),
    sa.Column('foto_storage_key', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.String(length=40), nullable=False),
    sa.CheckConstraint('valor_centavos > 0 AND volume_l BETWEEN 0.5 AND 1000', name='ck_abast_range'),
    sa.ForeignKeyConstraint(['combustivel_id'], ['combustivel.id'], ),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['posto_id'], ['posto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posto_id', sa.Integer(), nullable=False),
    sa.Column('combustivel_id', sa.Integer(), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.String(length=40), nullable=False),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('registrado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(length=16), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("fonte IN ('operador','bot','import_csv','ocr')", name='ck_preco_fonte'),
    sa.CheckConstraint('observed_at <= recorded_at', name='ck_preco_observed_le_recorded'),
    sa.CheckConstraint('valor_centavos > 0 AND valor_centavos < 5000000', name='ck_preco_valor_range'),
    sa.ForeignKeyConstraint(['combustivel_id'], ['combustivel.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['posto_id'], ['posto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preco', schema=None) as batch_op:
        batch_op.create_index('ix_preco_posto_combustivel_obs', ['posto_id', 'combustivel_id', 'observed_at'], unique=False)

    op.create_table('usuario_veiculo',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_perfil_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['veiculo_perfil_id'], ['veiculo_perfil.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'veiculo_perfil_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_veiculo')
    with op.batch_alter_table('preco', schema=None) as batch_op:
        batch_op.drop_index('ix_preco_posto_combustivel_obs')

    op.drop_table('preco')
    op.drop_table('abastecimento_relatado')
    op.drop_table('veiculo_perfil')
    op.drop_table('usuario_cidade')
    op.drop_table('tombstone_usuario')
    with op.batch_alter_table('posto', schema=None) as batch_op:
        batch_op.drop_index('ix_posto_cidade_ativo')

    op.drop_table('posto')
    op.drop_table('import_batch')
    op.drop_table('faixa_preco')
    with op.batch_alter_table('evento_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_criado')

    op.drop_table('evento_audit')
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_index('ix_consulta_usuario')
        batch_op.drop_index('ix_consulta_feita_em')

    op.drop_table('consulta')
    op.drop_table('bot_estado')
    op.drop_table('veiculo_tipo')
    op.drop_table('usuario')
    op.drop_table('owner_lease')
    op.drop_table('idempotency_key')
    op.drop_table('feature_flag')
    op.drop_table('combustivel')
    op.drop_table('cidade')
    # ### end Alembic commands ###
